projects:
  shoestore:
    schemaPath: src/graphql/schema.json
    includes:
      - 'type ShoppingCart @model {'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
